c++11: fix ambiguous 'ref()'
c++11 introduces std::ref() (part of all the functional additions).

Son now the namespace-less use of ref() in connection.hpp was ambiguous
and yielding the following error:

```
In file included from ../include/f8includes.hpp:67:0,
                 from xml.cpp:62:
../include/connection.hpp: In instantiation of 'FIX8::AsyncSocket<T>::AsyncSocket(Poco::Net::StreamSocket*, FIX8::Session&, FIX8::ProcessModel) [with T = std::basic_s
tring<char>]':
../include/connection.hpp:163:120:   required from here
../include/connection.hpp:70:72: error: call of overloaded 'ref(FIX8::AsyncSocket<std::basic_string<char> >&)' is ambiguous
../include/connection.hpp:70:72: note: candidates are:
In file included from ../include/f8includes.hpp:56:0,
                 from xml.cpp:62:
../include/thread.hpp:75:29: note: FIX8::reference_wrapper<T> FIX8::ref(T&) [with T = FIX8::AsyncSocket<std::basic_string<char> >]
In file included from /usr/include/c++/4.7/bits/stl_algo.h:68:0,
                 from /usr/include/c++/4.7/algorithm:63,
                 from xml.cpp:43:
/usr/include/c++/4.7/functional:486:10: note: void std::ref(const _Tp&&) [with _Tp = FIX8::AsyncSocket<std::basic_string<char> >] <near match>
/usr/include/c++/4.7/functional:486:10: note:   no known conversion for argument 1 from 'FIX8::AsyncSocket<std::basic_string<char> >' to 'const FIX8::AsyncSocket<std:
:basic_string<char> >&&'
/usr/include/c++/4.7/functional:476:5: note: std::reference_wrapper<_Tp> std::ref(_Tp&) [with _Tp = FIX8::AsyncSocket<std::basic_string<char> >]
```

The fix is simply to specify the FIX8 namespace for ref().